export const staticFeaturedJobs = [
    {
        id: 1,
        logoName: 'Amazon',
        location: 'Remote',
        workingTime: 'Full Time',
        company: 'Company Name',
        title: 'Job Title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum justo id malesuada congue.',
        tags: ['Skill Tag', 'Skill Tag'],
    },
    {
        id: 2,
        logoName: 'Quantum',
        location: 'Remote',
        workingTime: 'Full Time',
        company: 'Company Name',
        title: 'Job Title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum justo id malesuada congue.',
        tags: ['Skill Tag', 'Skill Tag'],
    },
    {
        id: 3,
        logoName: 'Amazon',
        location: 'Remote',
        workingTime: 'Full Time',
        company: 'Company Name',
        title: 'Job Title',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum justo id malesuada congue.',
        tags: ['Skill Tag', 'Skill Tag'],
    },
];
